name: Deploy Vue App to Kind

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: vue-app
      IMAGE_TAG: ${{ github.sha }}
      DEPLOYMENT_NAME: vue-deployment
      NAMESPACE: default

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Kind & kubectl
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Create Kind Cluster
        run: |
          kind create cluster --wait 60s

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Load Docker Image into Kind Cluster
        run: |
          kind load docker-image $IMAGE_NAME:$IMAGE_TAG

      - name: Render Kubernetes Manifest
        run: |
          export DOCKER_USERNAME=dummy  # Kind doesn't need this
          export IMAGE_TAG=${{ github.sha }}
          envsubst < ./k8s/k8s-deployment.yaml.template > ./k8s/k8s-deployment.yaml

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f ./k8s/k8s-deployment.yaml

      - name: Wait for Pod to Be Ready
        run: |
          kubectl wait --for=condition=ready pod -l app=vue --timeout=60s

      - name: Port Forward & Test HTTP Response
        run: |
          kubectl port-forward svc/vue-service 8080:80 &
          sleep 5  # Wait for the port-forward to start
          curl -f http://localhost:8080 || (echo "App is not responding!" && exit 1)

      - name: Get Pods
        run: |
          kubectl get pods
