name: Vue CI/CD to Kubernetes

on:
  workflow_dispatch:

env:
  IMAGE_NAME: vue-app
  IMAGE_TAG: ${{ github.sha }}
  REGISTRY: docker.io
  DEPLOYMENT_NAME: vue-deployment
  NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .
          docker push $REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Render Kubernetes Manifest
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          export IMAGE_TAG=${{ github.sha }}
          envsubst < ./k8s/k8s-deployment.yaml.template > ./k8s/k8s-deployment.yaml

      - name: Apply Kubernetes Manifest
        run: |
          kubectl apply -f ./k8s/k8s-deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME vue-container=$REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG --namespace $NAMESPACE
